# Generated by Django 6.0.3 on 2026-06-23 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_initial_plan(apps, schema_editor):
    Plan = apps.get_model("billing", "Plan")
    Plan.objects.get_or_create(
        name="Plano Inicial",
        defaults={
            "max_services_per_user": 30,
            "max_users_per_establishment": 5,
            "price": 0,
            "is_active": True,
        },
    )


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default="Plano Inicial", max_length=100, unique=True)),
                ("max_services_per_user", models.PositiveIntegerField(default=30)),
                ("max_users_per_establishment", models.PositiveIntegerField(default=5)),
                ("price", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("active", "Ativa"), ("pending", "Pendente"), ("canceled", "Cancelada"), ("expired", "Expirada")], default="active", max_length=20)),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("stripe_customer_id", models.CharField(blank=True, max_length=255)),
                ("stripe_subscription_id", models.CharField(blank=True, max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("plan", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="subscriptions", to="billing.plan")),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="subscription", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.RunPython(create_initial_plan, migrations.RunPython.noop),
    ]
