# Generated by Django 6.0.3 on 2026-06-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
