# Generated by Django 6.0.3 on 2026-06-24 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_plan_stripe_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='stripe_id',
            new_name='stripe_price_id',
        ),
    ]
