# Generated by Django 6.0.3 on 2026-04-15 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, unique=True),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=10)),
                ('complement', models.CharField(blank=True, max_length=255, null=True)),
                ('neighborhood', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=10)),
                ('establishment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='establishment.establishment')),
            ],
        ),
    ]
