# Generated by Django 6.0.3 on 2026-04-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0003_alter_establishment_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, unique=True),
        ),
    ]
