# Generated by Django 6.0.3 on 2026-04-28 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0006_alter_address_city_alter_address_complement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_address_publicly', models.BooleanField(default=True)),
                ('show_phone_publicly', models.BooleanField(default=True)),
                ('establishment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='general_preferences', to='establishment.establishment')),
            ],
        ),
    ]
