# Generated by Django 6.0.3 on 2026-05-10 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0007_generalpreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishment',
            name='description',
        ),
    ]
