# Generated by Django 6.0.3 on 2026-05-14 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0008_remove_establishment_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='complement',
        ),
    ]
