# Generated by Django 6.0.3 on 2026-05-14 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0009_remove_address_complement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalpreference',
            old_name='show_address_publicly',
            new_name='open_establishment',
        ),
    ]
