# Generated by Django 6.0.3 on 2026-05-20 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0010_rename_show_address_publicly_generalpreference_open_establishment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishment',
            name='cnpj',
        ),
    ]
