# Generated by Django 6.0.3 on 2026-05-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0012_alter_address_city_alter_address_neighborhood_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
