# Generated by Codex on 2026-05-19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0002_alter_appointment_service_delete_service"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diverses",
            name="interval_time",
        ),
    ]
