# Generated by Django 6.0.3 on 2026-05-20 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_remove_diverses_interval_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Diverses',
        ),
    ]
