# Generated by Django 6.0.3 on 2026-06-08 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_delete_diverses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoursunavailable',
            name='availability',
        ),
    ]
