# Generated by Django 6.0.3 on 2026-06-18 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
