# Generated by Django 6.0.3 on 2026-06-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_appointment_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('rejected', 'Recusado'), ('canceled', 'Cancelado')], default='confirmed', max_length=10),
        ),
    ]
