# Generated by Django 6.0.3 on 2026-03-29 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diverses',
            old_name='interval_times',
            new_name='interval_time',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='duracao',
            new_name='interval_time',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='preco',
            new_name='price',
        ),
    ]
