# Generated by Django 6.0.3 on 2026-03-29 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_rename_interval_times_diverses_interval_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='interval_time',
            new_name='time_duration',
        ),
    ]
