# Generated by Django 6.0.3 on 2026-03-30 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_rename_interval_time_service_time_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='nome_cliente',
            new_name='client_name',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='criado_em',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='data',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='observacoes',
            new_name='observation',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='telefone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='servico',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='horario',
            new_name='time',
        ),
    ]
