# Generated by Django 6.0.3 on 2026-04-03 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0004_rename_nome_cliente_appointment_client_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='duration',
            field=models.IntegerField(default=1, help_text='Duração em minutos'),
            preserve_default=False,
        ),
    ]
