# Generated by Django 6.0.3 on 2026-04-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0005_appointment_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='client_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='observation',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
