# Generated by Django 6.0.3 on 2026-06-24 14:16

import core.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=core.encryption.EncryptedEmailField(blank=True, max_length=255),
        ),
    ]
